### ISSUE TITLE
Running on Fedora 31

### ISSUE THREAD

**Issue by vikaspragy** [CodeBrig/Journey#34]
Not able to run the JourneyBrowser sample program : 
1. Project setup  on maven in net beans 11
2. Following is the result of run

cd /home/vikas/NetBeansProjects/mavenproject3; JAVA_HOME=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64 /home/vikas/Documents/DEVTools/incubating-netbeans-11.0-bin/netbeans/java/maven/bin/mvn "-Dexec.args=-classpath %classpath JourneyBrowser" -Dexec.executable=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.242.b08-0.fc31.x86_64/bin/java org.codehaus.mojo:exec-maven-plugin:1.5.0:exec
Running NetBeans Compile On Save execution. Phase execution is skipped and output directories of dependency projects (with Compile on Save turned on) will be used instead of their jar artifacts.
Scanning for projects...
                                                                        
------------------------------------------------------------------------
Building TestJourney 1.0-SNAPSHOT
------------------------------------------------------------------------

--- exec-maven-plugin:1.5.0:exec (default-cli) @ mavenproject3 ---
Exception in thread "main" java.lang.ExceptionInInitializerError
	at JourneyBrowser.main(JourneyBrowser.java:11)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
	at com.codebrig.journey.JourneyLoader.setup(JourneyLoader.java:204)
	at com.codebrig.journey.JourneyBrowserView.<clinit>(JourneyBrowserView.java:33)
	... 1 more
Caused by: java.lang.NullPointerException
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1847)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1124)
	at com.codebrig.journey.JourneyLoader.loadLinux(JourneyLoader.java:338)
	at com.codebrig.journey.JourneyLoader.setup(JourneyLoader.java:173)
	... 2 more
Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:764)
	at org.codehaus.mojo.exec.ExecMojo.executeCommandLine(ExecMojo.java:711)
	at org.codehaus.mojo.exec.ExecMojo.execute(ExecMojo.java:289)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
------------------------------------------------------------------------
BUILD FAILURE
------------------------------------------------------------------------
Total time: 0.415 s
Finished at: 2020-05-28T06:29:33+05:30
Final Memory: 18M/960M
------------------------------------------------------------------------
Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.5.0:exec (default-cli) on project mavenproject3: Command execution failed. Process exited with an error: 1 (Exit value: 1) -> [Help 1]

To see the full stack trace of the errors, re-run Maven with the -e switch.
Re-run Maven using the -X switch to enable full debug logging.

For more information about the errors and possible solutions, please read the following articles:
[Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException

**Comment by BFergerson** [comment]
Does running [this](https://github.com/CodeBrig/Journey#linux-64bit) work for you? Are you able to provide a reproducible example? 

Besides that, if you're using 0.4.0-offline there is a known issue with it (https://github.com/CodeBrig/Journey/issues/30).

**Comment by vikaspragy** [comment]
I tried with  0.4.0-online, v0.3.3. also, same error.  I will provide the complete maven project by today evening. It has never worked on my set setup on fedora 30/31.

**Comment by BFergerson** [comment]
@vikaspragy, how about https://github.com/CodeBrig/Journey#linux-64bit? This is just the JCEF project without using Journey. If that doesn't work then Journey isn't the issue. It'll help to know if that works first.
