### ISSUE TITLE
Error fat file

### ISSUE THREAD

**Issue by innoveratech** [CodeBrig/Journey#40]
#I am using v3.0.0, it's work in IDE, but have an error while running in single jar (fat) file with dependencies.
OS. Linux ubuntu 18.04 LTS
jdk 1.8

I think the error cause of missing in the  loading  of .so file.

====== Error ===========
java -jar my-project-name-jar-with-dependencies.jar 
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.codebrig.journey.JourneyLoader (file:/home/khalegh/Downloads/8/projectJavaChromeBrowserJavaEight/WEB/target/my-project-name-jar-with-dependencies.jar) to field java.lang.ClassLoader.sys_paths
WARNING: Please consider reporting this to the maintainers of com.codebrig.journey.JourneyLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Exception in thread "main" java.lang.ExceptionInInitializerError
        at net.khalegh.ShowBrowserDemo.main(ShowBrowserDemo.java:12)
Caused by: java.lang.RuntimeException: java.lang.NullPointerException
        at com.codebrig.journey.JourneyLoader.setup(JourneyLoader.java:204)
        at com.codebrig.journey.JourneyBrowserView.<clinit>(JourneyBrowserView.java:33)
        ... 1 more
Caused by: java.lang.NullPointerException
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2646)
        at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
        at java.base/java.lang.System.loadLibrary(System.java:1873)
        at com.codebrig.journey.JourneyLoader.loadLinux(JourneyLoader.java:338)
        at com.codebrig.journey.JourneyLoader.setup(JourneyLoader.java:173)
        ... 2 more

**Comment by innoveratech** [comment]
done. it's work.
